[package]
name = "alerter"
version = "0.1.0"
authors = ["ultram4rine <ultramarine730@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
telegram-bot = "0.8"
futures = "0.3"
tokio = { version="1.7", features=["full"] }
warp = "0.3"
serde = { version="1.0", features=["derive"] }
serde_json = "1.0"
dotenv = "0.15"
