#!/bin/sh

getent group alerter >/dev/null || groupadd -r alerter
getent passwd alerter >/dev/null || useradd -r -g alerter -d /usr/share/alrter -s /sbin/nologin -c "Telegram alerter for Alertmanager" alerter

#DEBHELPER#
