#!/bin/sh

set -e

getent group alerter >/dev/null || groupadd -r alerter
getent passwd alerter >/dev/null || useradd -r -g alerter -d /usr/share/alerter -s /sbin/nologin -c "Telegram bot for alerts from Alertmanager" alerter

#DEBHELPER#
