name: CI

on:
  push:
    paths-ignore:
      - ".github/workflows/release.yml"
      - ".github/workflows/pkg.yml"
      - ".github/dependabot.yml"
      - "LICENSE"
      - "*.md"
      - "test.sh"
  pull_request:
    paths-ignore:
      - ".github/workflows/release.yml"
      - ".github/workflows/pkg.yml"
      - ".github/dependabot.yml"
      - "LICENSE"
      - "*.md"
      - "test.sh"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - "x86_64-unknown-linux-gnu"
          - "armv7-unknown-linux-gnueabihf"
    steps:
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore cache
        uses: Swatinem/rust-cache@v1

      - name: Test
        uses: actions-rs/cargo@v1
        env:
          TARGET: ${{ matrix.target }}
        with:
          command: test
          args: --target ${{ matrix.target }}
          use-cross: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
          use-cross: true

      - name: Archive
        run: |
          mv target/${{ matrix.target }}/release/alerter .
          tar -czvf alerter-${{ matrix.target }}.tar.gz alerter templates

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: alerter-${{ matrix.target }}.tar.gz
          path: alerter-${{ matrix.target }}.tar.gz
