name: CI
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Restore cache
        uses: Swatinem/rust-cache@v1
      - name: Build
        run: cargo build --release
      - name: Setup cargo-generate-rpm
        run: cargo install cargo-generate-rpm
      - name: Make RPM package
        run: |
          strip -s target/release/alerter
          cargo generate-rpm
      - name: Upload binary artifact
        uses: actions/upload-artifact@v2
        with:
          path: target/release/alerter
      - name: Upload RPM artifact
        uses: actions/upload-artifact@v2
        with:
          path: target/generate-rpm/alerter-*.rpm
