name: CI/CD

on:
  push:
    paths-ignore:
      - ".github/workflows/docker.yml"
      - ".github/workflows/pkg.yml"
      - ".github/workflows/update-packagers.yml"
      - ".github/dependabot.yml"
      - "scripts/test.sh"
      - "templates"
      - "Dockerfile"
      - "LICENSE"
      - ".*ignore"
      - "*.md"
  pull_request:
    paths-ignore:
      - ".github/workflows/docker.yml"
      - ".github/workflows/pkg.yml"
      - ".github/workflows/update-packagers.yml"
      - ".github/dependabot.yml"
      - "scripts/test.sh"
      - "templates"
      - "Dockerfile"
      - "LICENSE"
      - ".*ignore"
      - "*.md"

jobs:
  test-n-build:
    name: Test and build
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore cache
        uses: Swatinem/rust-cache@v1

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Archive
        run: |
          mv target/release/alerter .
          tar -czvf alerter-$(cargo read-manifest | jq -r .version).tar.gz alerter templates

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: alerter-archive
          path: alerter-*.tar.gz

  package:
    name: Package
    needs: test-n-build
    uses: ./.github/workflows/pkg.yml

  release:
    name: Release
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - test-n-build
      - package
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create release body file
        run: awk -v ver=$(cargo read-manifest | jq -r .version) '/^#+ \[/ { if (p) { exit }; if ($2 == "["ver"]") { p=1; next } } p && NF' CHANGELOG.md > changes.txt

      - name: Download archive
        uses: actions/download-artifact@v3
        with:
          name: alerter-archive
          path: archive

      - name: Download Deb package
        uses: actions/download-artifact@v3
        with:
          name: alerter-deb
          path: packages

      - name: Download RPM package
        uses: actions/download-artifact@v3
        with:
          name: alerter-rpm
          path: packages

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: changes.txt
          files: |
            archive/alerter-*.tar.gz
            packages/**/*

  publish_crate:
    name: Publish crate
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - test-n-build
      - package
    steps:
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore cache
        uses: Swatinem/rust-cache@v1

      - name: Login to crates.io
        uses: actions-rs/cargo@v1
        with:
          command: login
          args: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish to crates.io
        uses: actions-rs/cargo@v1
        with:
          command: publish
