name: CICD

on:
  push:
    paths-ignore:
      - ".github/dependabot.yml"
      - "LICENSE"
      - "*.md"
      - "test.sh"
  pull_request:
    paths-ignore:
      - ".github/dependabot.yml"
      - "LICENSE"
      - "*.md"
      - "test.sh"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Restore cache
        uses: Swatinem/rust-cache@v1
      - name: Build
        run: cargo build --release
      - name: Setup cargo-generate-rpm
        run: cargo install cargo-generate-rpm
      - name: Make RPM package
        run: |
          strip -s target/release/alerter
          cargo generate-rpm
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            target/release/alerter
            target/generate-rpm/alerter-*.rpm
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifacts
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/alerter
            generate-rpm/alerter-*.rpm
