name: CI/CD

on:
  push:
    paths-ignore:
      - ".github/workflows/release.yml"
      - ".github/workflows/pkg.yml"
      - ".github/dependabot.yml"
      - "LICENSE"
      - "*.md"
      - "test.sh"
  pull_request:
    paths-ignore:
      - ".github/workflows/release.yml"
      - ".github/workflows/pkg.yml"
      - ".github/dependabot.yml"
      - "LICENSE"
      - "*.md"
      - "test.sh"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore cache
        uses: Swatinem/rust-cache@v1

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Archive
        run: |
          mv target/release/alerter .
          tar -czvf alerter.tar.gz alerter templates

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: alerter-archive
          path: alerter.tar.gz

  package:
    name: Package
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/pkg.yml

  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build
      - package
    steps:
      - name: Download archive
        uses: actions/download-artifact@v3
        with:
          name: alerter-archive
          path: archive

      - name: Download Deb package
        uses: actions/download-artifact@v3
        with:
          name: alerter-deb
          path: packages

      - name: Download RPM package
        uses: actions/download-artifact@v3
        with:
          name: alerter-rpm
          path: packages

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          fail_on_unmatched_files: true
          files: |
            archive/alerter.tar.gz
            packages/**/*
