name: Docker image

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      GITHUB_TOKEN:
        required: true
  push:
    branches:
      - master
    paths-ignore:
      - ".github/workflows/cicd.yml"
      - ".github/workflows/pkg.yml"
      - ".github/dependabot.yml"
      - "templates"
      - "LICENSE"
      - "*.md"
      - "test.sh"
  pull_request:
    paths-ignore:
      - ".github/workflows/cicd.yml"
      - ".github/workflows/pkg.yml"
      - ".github/dependabot.yml"
      - "templates"
      - "LICENSE"
      - "*.md"
      - "test.sh"

jobs:
  build:
    name: Build image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set docker image tag
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "DOCKER_TAG=:$(cargo read-manifest | sed 's/.*"version":"\{0,1\}\([^,"]*\)"\{0,1\}.*/\1/')" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ultram4rine/alerter:latest
            ghcr.io/ultram4rine/alerter:latest
            ultram4rine/alerter${{ env.DOCKER_TAG }}
            ghcr.io/ultram4rine/alerter${{ env.DOCKER_TAG }}
