name: Packaging

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - ".github/workflows/pkg.yml"
    branches:
      - master
  pull_request:
    paths:
      - ".github/workflows/pkg.yml"

jobs:
  deb:
    name: Deb package
    env:
      CARGO_DEB_VER: 1.38.1
      DEBIAN_FRONTEND: noninteractive
      PKG_CONFIG_ALLOW_CROSS: 1
    strategy:
      matrix:
        target:
          - "x86_64-unknown-linux-gnu"
          - "armv7-unknown-linux-gnueabihf"
    runs-on: ubuntu-20.04
    steps:
      - name: Install common libs
        run: |
          sudo apt-get update
          sudo apt-get install pkg-config libssl-dev lintian

      - name: Install libs for ARMv7
        if: matrix.target == 'armv7-unknown-linux-gnueabihf'
        run: |
          sudo dpkg --add-architecture armhf
          sudo sed 's/deb http/deb \[arch=amd64,i386\] http/' -i /etc/apt/sources.list
          sudo tee -a /etc/apt/sources.list > /dev/null <<EOF
          deb [arch=armhf] http://ports.ubuntu.com/ focal main universe restricted multiverse
          deb [arch=armhf] http://ports.ubuntu.com/ focal-updates main universe restricted multiverse
          deb [arch=armhf] http://ports.ubuntu.com/ focal-security main universe restricted multiverse
          EOF

          sudo apt-get update
          sudo apt-get install -y libssl-dev:armhf gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore cache
        uses: Swatinem/rust-cache@v1
        with:
          key: ${{ matrix.target }}

      - name: Install Cargo Deb
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-deb --vers=${{ env.CARGO_DEB_VER }} --locked

      - name: Create debian changelog
        run: |
          python scripts/kac2debian_changelog.py --input CHANGELOG.md --output pkg/doc/changelog --package-name alerter --author ultram4rine --email ultramarine730@gmail.com

      - name: Generate man page
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --bin=mangen

      - name: Create package
        uses: actions-rs/cargo@v1
        with:
          command: deb
          args: --target=${{ matrix.target }}

      - name: Verify package
        run: |
          # do not use exit codes while errors occured
          lintian -v target/${{ matrix.target }}/debian/*.deb || true

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: alerter-deb
          path: |
            target/${{ matrix.target }}/debian/*.deb

  rpm:
    name: RPM package
    env:
      CARGO_GENERATE_RPM_VER: 0.6.0
    strategy:
      matrix:
        image:
          - "centos:7"
          - "fedora:34"
    runs-on: ubuntu-20.04
    container:
      image: ${{ matrix.image }}
    steps:
      - name: Install libs on CentOS
        if: startsWith(matrix.image, 'centos')
        run: |
          yum update -y && yum install -y epel-release && yum install -y gcc make cmake3 gcc-c++ openssl-devel gzip rpmlint
          ln -s /usr/bin/cmake3 /usr/bin/cmake

      - name: Install libs on Fedora
        if: startsWith(matrix.image, 'fedora')
        run: dnf install --refresh -y gcc cmake gcc-c++ openssl-devel gzip rpmlint

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore cache
        uses: Swatinem/rust-cache@v1
        with:
          key: ${{ matrix.image }}

      - name: Delete previous RPM
        run: rm -f target/generate-rpm/*.rpm

      - name: Install Cargo Generate RPM
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-generate-rpm --vers=${{ env.CARGO_GENERATE_RPM_VER }} --locked

      - name: Generate man page
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --bin=mangen

      - name: Compress man page
        run: |
          gzip -c pkg/doc/alerter.1 > pkg/doc/alerter.1.gz

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Remove all symbol and relocation information
        run: strip -s target/release/alerter

      - name: Set compress type for CentOS 7
        if: matrix.image == 'centos:7'
        run: echo "CENTOS_BUILD_FLAGS=--payload-compress=gzip" >> $GITHUB_ENV

      - name: Add dist to release
        run: dist=$(rpm --eval %{?dist}); sed -i -e 's/release = "\(.*\)"/release = "\1'$dist'"/g' Cargo.toml

      - name: Create package
        uses: actions-rs/cargo@v1
        with:
          command: generate-rpm
          args: ${{ env.CENTOS_BUILD_FLAGS }}

      - name: Verify package
        run: |
          # do not use exit codes while errors occured
          rpmlint target/generate-rpm/alerter-*.rpm || true

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: alerter-rpm
          path: |
            target/generate-rpm/alerter-*.rpm
