name: Packaging

on: [workflow_dispatch, workflow_call]

jobs:
  deb:
    name: Deb package
    env:
      CARGO_DEB_VER: 1.36.0
    strategy:
      matrix:
        image:
          - "ubuntu:20.04"
        target:
          - "x86_64-unknown-linux-gnu"
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    steps:
      - name: Set vars
        id: setvars
        run: echo "CARGO_BUILD_TARGET=${MATRIX_TARGET}" >> $GITHUB_ENV
        env:
          MATRIX_TARGET: ${{ matrix.target }}

      - name: Install libs
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt-get update
          apt-get install -y curl build-essential libssl-dev pkg-config lintian

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Cargo Deb if available
        id: cache-cargo-deb
        if: env.OS_NAME == 'ubuntu'
        uses: actions/cache@v2
        with:
          path: ~/.cargo/bin/cargo-deb
          key: cargo-deb-${{ env.CARGO_DEB_VER }}-${{ matrix.target }}

      - name: Install Cargo Deb if needed
        if: env.OS_NAME == 'ubuntu' && steps.cache-cargo-deb.outputs.cache-hit != 'true'
        uses: actions-rs/cargo@v1
        env:
          CARGO_TARGET: ${{ matrix.target }}
        with:
          command: install
          args: cargo-deb --vers=${{ env.CARGO_DEB_VER }} --locked --target=${{ env.CARGO_TARGET }}

      - name: Restore cache
        uses: Swatinem/rust-cache@v1

      - name: Create package
        uses: actions-rs/cargo@v1
        with:
          command: deb
          args: --target ${CARGO_BUILD_TARGET}

      - name: Verify package
        run: |
          # do not use exis codes while errors occured
          lintian -v target/debian/*.deb || true

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: alerter-deb
          path: |
            target/debian/*.deb

  rpm:
    name: RPM package
    env:
      CARGO_GENERATE_RPM_VER: 0.6.0
    strategy:
      matrix:
        image:
          - "fedora:34"
        target:
          - "x86_64-unknown-linux-gnu"
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    steps:
      - name: Set vars
        id: setvars
        run: echo "CARGO_BUILD_TARGET=${MATRIX_TARGET}" >> $GITHUB_ENV
        env:
          MATRIX_TARGET: ${{ matrix.target }}

      - name: Install libs
        env:
          DEBIAN_FRONTEND: noninteractive
        run: dnf install -y gcc cmake openssl-devel rpmlint

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.triple.target }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Cargo Generate RPM if available
        id: cache-cargo-generate-rpm
        if: env.OS_NAME == 'fedora'
        uses: actions/cache@v2
        with:
          path: ~/.cargo/bin/cargo-generate-rpm
          key: cargo-generate-rpm-${{ env.CARGO_GENERATE_RPM_VER }}-${{ matrix.target }}

      - name: Install Cargo Generate RPM if needed
        if: env.OS_NAME == 'fedora' && steps.cache-cargo-generate-rpm.outputs.cache-hit != 'true'
        uses: actions-rs/cargo@v1
        env:
          CARGO_TARGET: ${{ matrix.target }}
        with:
          command: install
          args: cargo-generate-rpm --vers=${{ env.CARGO_GENERATE_RPM_VER }} --locked --target=${{ env.CARGO_TARGET }}

      - name: Restore cache
        uses: Swatinem/rust-cache@v1

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${CARGO_BUILD_TARGET}

      - name: Remove all symbol and relocation information
        run: strip -s target/release/alerter

      - name: Create package
        uses: actions-rs/cargo@v1
        with:
          command: generate-rpm
          args: --target ${CARGO_BUILD_TARGET}

      - name: Verify package
        run: |
          # do not use exis codes while errors occured
          rpmlint target/generate-rpm/*.rpm || true

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: alerter-rpm
          path: |
            target/generate-rpm/*.rpm
