name: Packaging

on: [workflow_dispatch, workflow_call]

jobs:
  deb:
    name: Deb package
    env:
      CARGO_DEB_VER: 1.36.0
    strategy:
      matrix:
        target:
          - "x86_64-unknown-linux-gnu"
          - "armv7-unknown-linux-gnueabihf"
    runs-on: ubuntu-latest
    steps:
      - name: Install libs on x86-64
        if: startsWith(matrix.target, 'arm') != true
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc pkg-config libssl-dev lintian

      - name: Install libs on ARM
        if: startsWith(matrix.target, 'arm')
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf lintian

      - name: Cache OpenSSL on ARM
        if: startsWith(matrix.target, 'arm')
        id: cache-openssl-arm
        uses: actions/cache@v2
        with:
          path: /tmp/openssl-1.1.1m/
          key: openssl-1.1.1m-${{ matrix.target }}

      - name: Install OpenSSL on ARM
        if: startsWith(matrix.target, 'arm') && steps.cache-openssl-arm.outputs.cache-hit != 'true'
        run: |
          cd /tmp
          wget https://www.openssl.org/source/openssl-1.1.1m.tar.gz
          echo "f89199be8b23ca45fc7cb9f1d8d3ee67312318286ad030f5316aca6462db6c96  openssl-1.1.1m.tar.gz" | sha256sum -c
          tar xzf openssl-1.1.1m.tar.gz
          export MACHINE=armv7
          export ARCH=arm
          export CC=arm-linux-gnueabihf-gcc
          cd openssl-1.1.1m && ./config shared && make && cd -

      - name: Set OpenSSL env vars on ARM
        if: startsWith(matrix.target, 'arm')
        run: |
          echo "OPENSSL_LIB_DIR=/tmp/openssl-1.1.1m/" >> $GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=/tmp/openssl-1.1.1m/include" >> $GITHUB_ENV

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore cache
        uses: Swatinem/rust-cache@v1

      - name: Install Cargo Deb
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-deb --vers=${{ env.CARGO_DEB_VER }} --locked

      - name: Create package
        uses: actions-rs/cargo@v1
        with:
          command: deb
          args: --target=${{ matrix.target }}

      - name: Verify package
        run: |
          # do not use exit codes while errors occured
          lintian -v target/${{ matrix.target }}/debian/*.deb || true

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: alerter-deb
          path: |
            target/${{ matrix.target }}/debian/*.deb

  rpm:
    name: RPM package
    env:
      CARGO_GENERATE_RPM_VER: 0.6.0
    runs-on: ubuntu-latest
    container:
      image: "fedora:34"
    steps:
      - name: Install libs
        run: dnf install --refresh -y gcc cmake openssl-devel rpmlint

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore cache
        uses: Swatinem/rust-cache@v1

      - name: Delete previous RPM
        run: rm -f target/generate-rpm/*.rpm

      - name: Install Cargo Generate RPM
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-generate-rpm --vers=${{ env.CARGO_GENERATE_RPM_VER }} --locked

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Remove all symbol and relocation information
        run: strip -s target/release/alerter

      - name: Create package
        uses: actions-rs/cargo@v1
        with:
          command: generate-rpm

      - name: Verify package
        run: |
          # do not use exit codes while errors occured
          rpmlint target/generate-rpm/*.rpm || true

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: alerter-rpm
          path: |
            target/generate-rpm/*.rpm
