name: Packaging

on: [workflow_dispatch]

jobs:
  pkg:
    env:
      CARGO_DEB_VER: 1.36.0
      CARGO_GENERATE_RPM_VER: 0.6.0
    strategy:
      matrix:
        image:
          - "ubuntu:20.04"
          - "fedora:34"
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    steps:
      - name: Set vars
        id: setvars
        run: |
          IMAGE="${MATRIX_IMAGE}"
          echo "OS_NAME=${IMAGE%:*}" >> $GITHUB_ENV
        env:
          MATRIX_IMAGE: ${{ matrix.image }}
      - name: Install libs
        env:
          MATRIX_IMAGE: ${{ matrix.image }}
        run: |
          case ${OS_NAME} in
            ubuntu)
              apt-get update
              apt-get install -y curl build-essential libssl-dev pkg-config
              ;;
            fedora)
              dnf install -y gcc cmake openssl-devel
              ;;
          esac
      - name: Setup Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --profile minimal -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Cargo Deb if needed
        if: steps.cache-cargo-deb.outputs.cache-hit != 'true'
        run: cargo install cargo-deb --version ${CARGO_DEB_VER} --locked
      - name: Install Cargo Generate RPM if needed
        if: steps.cache-cargo-generate-rpm.outputs.cache-hit != 'true'
        run: cargo install cargo-generate-rpm --version ${CARGO_GENERATE_RPM_VER} --locked
      - name: Create package
        run: |
          case ${OS_NAME} in
            ubuntu)
              cargo deb
              ;;
            fedora)
              cargo build --release
              strip -s target/release/alerter
              cargo generate-rpm
              ;;
          esac
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: alerter-${{ env.OS_NAME }}
          path: |
            target/debian/*.deb
            target/generate-rpm/*.rpm
