name: Release

on:
  release:
    types:
      - created

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Archive
        run: |
          mv target/release/alerter .
          tar -czvf alerter.tar.gz alerter templates
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: alerter.tar.gz

  package:
    name: Package
    uses: ./.github/workflows/pkg.yml

  upload_artifacts:
    name: Upload artifacts to releasse
    runs-on: ubuntu-latest
    needs:
      - build
      - package
    steps:
      - name: Download binary
        uses: actions/download-artifact@v3
        with:
          name: alerter
          path: binary
      - name: Download Deb package
        uses: actions/download-artifact@v3
        with:
          name: alerter-ubuntu
          path: packages
      - name: Download RPM package
        uses: actions/download-artifact@v3
        with:
          name: alerter-fedora
          path: packages
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: binary/alerter
          tag: ${{ github.ref }}
      - name: Upload packages to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: packages/**/*
          file_glob: true
          tag: ${{ github.ref }}
