name: Update packagers

on:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  check-for-updates:
    name: Check cargo-deb and cargo-generate-rpm updates
    runs-on: ubuntu-20.04
    env:
      DEBIAN_FRONTEND: noninteractive
    strategy:
      fail-fast: false
      matrix:
        packager: [cargo-deb, cargo-generate-rpm]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install jq
        run: |
          sudo apt update
          sudo apt install -y jq
      - name: Get versions and set env vars
        run: |
          case ${{ matrix.packager }} in
            cargo-deb)
              echo "VER_NAME='CARGO_DEB_VER'" >> $GITHUB_ENV
              echo "REPO_URL='https://github.com/kornelski/cargo-deb'" >> $GITHUB_ENV
              ;;

            cargo-generate-rpm)
              echo "VER_NAME='CARGO_GENERATE_RPM_VER'" >> $GITHUB_ENV
              echo "REPO_URL='https://github.com/cat-in-136/cargo-generate-rpm'" >> $GITHUB_ENV
              ;;
          esac

          echo 'OLD_VER=$(cat .github/workflows/pkg.yml | sed -n "s/.*$VER_NAME: \(.*\)/\1/p")' >> $GITHUB_ENV

          echo "NEW_VER=$(curl -s -X GET https://crates.io/api/v1/crates/${{ matrix.packager }} | jq '.versions[0].num' | tr -d '"')" >> $GITHUB_ENV

      - name: Make changes to pkg workflow
        if: env.OLD_VER != env.NEW_VER
        run: |
          sed -i "s/\(\s$VER_NAME: \)\(.*\)/\1$NEW_VER/g" .github/workflows/pkg.yml

      - name: Create Pull Request
        if: env.OLD_VER != env.NEW_VER
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Bump ${{ matrix.packager }} from ${{ env.OLD_VER }} to ${{ env.NEW_VER }}
          branch: cargo/${{ matrix.packager }}-${{ env.NEW_VER }}
          delete-branch: true
          title: "Bump ${{ matrix.packager }} from ${{ env.OLD_VER }} to ${{ env.NEW_VER }}"
          body: |
            Bumps [${{ matrix.packager }}](${{ env.REPO_URL }}) from ${{ env.OLD_VER }} to ${{ env.NEW_VER }}.
          labels: |
            dependencies
            rust
